mode: rule
log-level: info
subscribe-url: &suburl http://example.com

proxy-providers:
  Australia:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¦ğŸ‡º|Australia|AU|æ¾³)
  Brazil:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡§ğŸ‡·|Brazil|BR|å·´)
  Canada:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¨ğŸ‡¦|Canada|CA|åŠ )
  Colombia:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¨ğŸ‡´|Colombia|CO|å“¥)
  Germany:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡©ğŸ‡ª|Germany|DE|å¾·)
  France:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡«ğŸ‡·|France|FR|æ³•)
  Hong Kong:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡­ğŸ‡°|Hong Kong|HK|æ¸¯)
  Iceland:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡®ğŸ‡¸|Iceland|IS|å†°)
  India:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡®ğŸ‡³|India|IN|å°)
  Indonesia:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡®ğŸ‡©|Indonesia|ID|å°¼)
  Japan:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¯ğŸ‡µ|Japan|JP|æ—¥)
  Korea:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡°ğŸ‡·|Korea|KR|éŸ©)
  Malaysia:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡²ğŸ‡¾|Malaysia|MY|æ¥)
  Singapore:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¸ğŸ‡¬|Singapore|SG|å¡)
  Taiwan:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¹ğŸ‡¼|Taiwan|TW|å°)
  Thailand:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¹ğŸ‡­|Thailand|TH|æ³°)
  United Arab Emirates:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¦ğŸ‡ª|United Arab Emirates|AE|ä¼¯)
  United Kingdom:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡¬ğŸ‡§|United Kingdom|GB|è‹±)
  United States:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡ºğŸ‡¸|United States|US|ç¾)
  Viet Nam:
    url: *suburl
    interval: 86400
    filter: (?i)(ğŸ‡»ğŸ‡³|Viet Nam|VN|è¶Š)
proxy-groups:
- name: $tash
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/bypass.png
  type: select
  proxies:
  - Auto
  - Available
  - Load Balance
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Auto
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/auto.png
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Available
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/available.png
  type: fallback
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
- name: Load Balance
  icon: https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/roundrobin.png
  type: load-balance
  strategy: consistent-hashing
  url: http://www.gstatic.com/generate_204
  interval: 300
  use:
  - Australia
  - Brazil
  - Canada
  - Colombia
  - France
  - Hong Kong
  - Iceland
  - India
  - Indonesia
  - Japan
  - Korea
  - Malaysia
  - Singapore
  - Taiwan
  - United Arab Emirates
  - United Kingdom
  - United States
  - Viet Nam
rules:
- GEOIP,CN,DIRECT
- MATCH,$tash
